[package]
name = "dql"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "data agnostic query language"

[dependencies]
dyn-clone = "1.0.19"
parse_duration = "2.1.1"

[dev-dependencies]
serde_json = "1.0.140"
